theme = "base16_transparent"

[editor]
line-number = "relative"
mouse = false
auto-format = false
bufferline = 'multiple'
scrolloff = 10
color-modes = true


[editor.statusline]
left = ["mode", "spinner", "version-control", "file-name", "file-modification-indicator"]
right = ["diagnostics", "selections", "position", "file-encoding", "file-type"]
mode.normal = 'NORMAL'
mode.insert = 'INSERT'
mode.select = 'SELECT'

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.indent-guides]
render = false

[editor.soft-wrap]
enable = true

[keys.normal]
';' = 'command_mode'
'space' = { ';' = 'collapse_selection' }
# colemak-dh
n = 'move_char_left'
e = 'move_visual_line_down'
i = 'move_visual_line_up'
o = 'move_char_right'
h = 'search_next'
j = 'move_next_word_end'
J = 'move_next_long_word_end'
k = 'insert_mode'
K = 'insert_at_line_start'
l = 'open_below'
L = 'open_above'

[keys.select]
n = 'extend_char_left'
e = 'extend_visual_line_down'
i = 'extend_visual_line_up'
o = 'extend_char_right'
h = 'extend_search_next'
H = 'extend_search_prev'
j = 'extend_next_word_end'
J = 'extend_next_long_word_end'
k = 'insert_mode'
K = 'insert_at_line_start'
l = 'open_below'
L = 'open_above'
