-- don't need to be set when the theme supports transparency (tends to mess stuff up)
--vim.cmd('highlight Normal guibg=#0a0a10 guifg=#dbdbdb')
--vim.cmd('highlight NonText guibg=#0a0a10 guifg=#0a0a10')
vim.cmd('highlight CursorLine guibg=#0e1e22')
vim.cmd('highlight CursorLineNr guifg=#ae81ff')
